#!/bin/bash

SOURCE_DIR=~/work/qi/code
BUILD_DIR=~/work/build
DATA_DIR=~/work/qi/data
THIRDPARTY=~/work/qi/thirdparty

SOURCES_QI="$SOURCE_DIR/qi.cpp $SOURCE_DIR/qi_debug.cpp $SOURCE_DIR/qi_sound.cpp $SOURCE_DIR/qi_math.cpp $SOURCE_DIR/qi_tile.cpp $SOURCE_DIR/qi_profile.cpp"
SOURCES_MAIN="$SOURCE_DIR/osx_qi.mm $SOURCE_DIR/qi_ogl.cpp"

pushd $BUILD_DIR

# Debug build
DVERSION=1.0
DEFINES="-DQI_DEV_BUILD=1 -DQI_OSX_BUILD=1 -DQI_PROFILE_BUILD=1 -DQI_DEV_DATA_DIR=\"$DATA_DIR\""
OPTIMIZATIONS=
DEBUG=-g
ALLBUILDOPTS="-std=c++17 -fms-extensions -fvisibility=hidden -fvisibility-inlines-hidden"

# Fast profile build
# DEFINES= "-DQI_FAST_BUILD=1 -DQI_OSX=1 -DQI_PROFILE_BUILD=1"
# OPTIMIZATIONS=-O2
# DEBUG=
# ALLBUILDOPTS=

# Release build
# DEFINES= "-DQI_FAST_BUILD=1 -DQI_OSX=1"
# OPTIMIZATIONS=-O2
# DEBUG=
# ALLBUILDOPTS=

INCLUDE_DIRS="-I$THIRDPARTY/include"
WARNINGS=

LINK_OPTS="-L$THIRDPARTY/lib/osx"
LIBS="-framework Cocoa -lglad"

clang++ $ALLBUILDOPTS $WARNINGS $OPTIMIZATIONS $DEBUG $DEFINES $INCLUDE_DIRS $LINK_OPTS -dynamiclib -current_version $DVERSION -compatibility_version $DVERSION $SOURCES_QI -o $BUILD_DIR/qi.dylib
clang++ $ALLBUILDOPTS $WARNINGS $OPTIMIZATIONS $DEBUG $DEFINES $INCLUDE_DIRS $LINK_OPTS $LIBS $SOURCES_MAIN -o $BUILD_DIR/osx_qi

popd

cp $SOURCE_DIR/*.glsl $DATA_DIR
